spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: approve
    url: jdbc:mysql://localhost:3306/dbname?useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    #连接池配置
    initialSize:  1
    minIdle: 1
    maxActive: 20
    #连接等待超时时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000

mybatis:
  mapper-locations: classpath:mapping/*.xml,classpath:mapping-manual/*xml
  type-aliases-package: com.xdd.entity
  configuration:
    map-underscore-to-camel-case: true





